namespace NuclearOptionSDK.Studio.Services;

public static partial class NoGameParameterCatalog
{
    private static Entry[] BuildCuratedEntries() =>
    [
        E("Telemetry.AoA", "Angle of attack (AoA)", "Degrees from AoADisplay formula (Atan2 velocity).", Direction.Read, Category.FlightTelemetry, "float", "derived:AoADisplay", "10", Q("0", "8", "10", "12", "15", "18", "20", "25", "30")),
        E("Telemetry.Speed", "Speed", "Aircraft speed m/s (Aircraft.speed).", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.speed", "80", Q("0", "10", "50", "80", "100", "150")),
        E("Telemetry.Altitude", "Altitude AGL", "Radar altitude (Unit.radarAlt).", Direction.Read, Category.FlightTelemetry, "float", "Unit.radarAlt", "100", Q("0", "0.2", "1", "5", "10", "50", "100", "500")),
        E("Telemetry.AbsAltitude", "Altitude MSL", "Absolute world Y altitude, m.", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.transform.position.y"),
        E("Telemetry.G", "G-load", "Current g-load (Aircraft.gForce).", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.gForce", "3", Q("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
        E("Telemetry.Fuel", "Fuel", "Fuel level 0–1 (fuelLevel).", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.fuelLevel", "0.15", Q("0.05", "0.1", "0.15", "0.2", "0.25", "0.5", "1")),
        E("Telemetry.FuelTime", "Time to empty", "Remaining flight time by burn rate (MKMods pattern).", Direction.Read, Category.FlightTelemetry, "float", "derived:fuel/rate", "7", Q("1", "3", "5", "7", "10", "15", "30")),
        E("Telemetry.Rpm", "Engine RPM", "Active engine RPM (IEngine.GetRPM).", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.engineStates", "80", Q("0", "50", "70", "80", "90", "100")),
        E("Telemetry.Throttle", "Throttle", "Throttle position 0–1 (ControlInputs.throttle).", Direction.Read, Category.FlightTelemetry, "float", "ControlInputs.throttle", "0.75", Q("0", "0.25", "0.5", "0.75", "1")),
        E("Telemetry.Collective", "Collective", "Helicopter collective 0–1.", Direction.Read, Category.FlightTelemetry, "float", "ControlInputs (helo)", "0.5", Q("0", "0.25", "0.5", "0.75", "1")),
        E("Telemetry.Heading", "Heading", "Heading 0–360° (Bearing / compass).", Direction.Read, Category.FlightTelemetry, "float", "FlightHud.compass.uvRect", "0", Q("0", "90", "180", "270", "360")),
        E("Telemetry.VerticalSpeed", "Vertical speed", "V/S m/s (Climbrate).", Direction.Read, Category.FlightTelemetry, "float", "Climbrate", "0", Q("-20", "-10", "0", "10", "20")),
        E("Telemetry.Mach", "Mach number", "MachIndicator.", Direction.Read, Category.FlightTelemetry, "float", "MachIndicator"),
        E("Telemetry.GearDown", "Gear down", "gearDeployed / gearState.", Direction.Read, Category.FlightTelemetry, "bool", "Aircraft.gearDeployed"),
        E("Telemetry.FlightAssist", "Flight Assist", "FA mode on/off.", Direction.Read, Category.FlightTelemetry, "bool", "Aircraft.flightAssist"),
        E("Telemetry.Ignition", "Ignition", "Engine running.", Direction.Read, Category.FlightTelemetry, "bool", "Aircraft.Ignition"),
        E("Telemetry.Damage", "Damage", "Part damage state (PartDamageTracker).", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.partDamageTracker", "0.5", Q("0.1", "0.25", "0.5", "0.75", "1")),
        E("Telemetry.RCS", "RCS", "Radar cross section (Unit.RCS). DinamicRCS mod.", Direction.Read, Category.FlightTelemetry, "float", "Unit.RCS"),
        E("Telemetry.ECM", "ECM intensity", "ECM level (ecmIntensity).", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.ecmIntensity", "0", Q("0", "0.25", "0.5", "0.75", "1")),
        E("Telemetry.Disabled", "Destroyed", "Unit.disabled.", Direction.Read, Category.FlightTelemetry, "bool", "Unit.disabled"),
        E("Telemetry.WingAngle", "Wing angle", "Swing wing / WingAngleGauge.", Direction.Read, Category.FlightTelemetry, "float", "WingAngleGauge"),
        E("Telemetry.Nozzle", "Nozzle position", "NozzleGauge (VTOL/afterburner).", Direction.Read, Category.FlightTelemetry, "float", "NozzleGauge"),
        E("Telemetry.CustomAxis1", "Custom axis 1", "Custom axis (CustomAxis1Gauge).", Direction.Read, Category.FlightTelemetry, "float", "ControlInputs.customAxis1"),
        E("Telemetry.TimeSinceLoad", "Time since load", "Seconds since sortie start.", Direction.Read, Category.FlightTelemetry, "float", "Time.time", "0", Q("0", "1", "5", "10", "30", "60")),
        E("Cockpit.velocity", "Velocity vector", "cockpit.rb.velocity (Vector3).", Direction.Read, Category.FlightTelemetry, "Vector3", "Aircraft.cockpit.rb.velocity"),
        E("Cockpit.radarAlt", "Radar alt (cockpit)", "Same as Telemetry.Altitude.", Direction.Read, Category.FlightTelemetry, "float", "Unit.radarAlt"),
        E("Cockpit.throttle", "Throttle (cockpit)", "ControlInputs.throttle.", Direction.Read, Category.PilotInputs, "float", "Aircraft.GetInputs().throttle"),
        E("Cockpit.fuel", "Fuel (cockpit)", "GetFuelLevel().", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.GetFuelLevel()"),
        E("Cockpit.gearDown", "Gear", "gearDeployed.", Direction.Read, Category.FlightTelemetry, "bool", "Aircraft.gearDeployed"),
        E("Cockpit.selectedWeapon", "Selected weapon", "Current station name (NO_Tactitools).", Direction.Read, Category.Weapons, "string", "WeaponManager.currentWeaponStation.WeaponInfo"),
        E("Input.Pitch", "Pitch", "Pitch −1…1.", Direction.Read, Category.PilotInputs, "float", "ControlInputs.pitch", "0", Q("-1", "-0.5", "0", "0.5", "1")),
        E("Input.Roll", "Roll", "Roll −1…1.", Direction.Read, Category.PilotInputs, "float", "ControlInputs.roll"),
        E("Input.Yaw", "Yaw", "Yaw −1…1.", Direction.Read, Category.PilotInputs, "float", "ControlInputs.yaw"),
        E("Input.Brake", "Brake", "Wheel brake 0–1.", Direction.Read, Category.PilotInputs, "float", "ControlInputs.brake"),
        E("Weapon.Ammo", "Station ammo", "Current WeaponStation ammo.", Direction.Read, Category.Weapons, "int", "WeaponStation.Ammo", "4", Q("0", "1", "2", "4", "8")),
        E("Weapon.MaxAmmo", "Max ammo", "Station FullAmmo.", Direction.Read, Category.Weapons, "int", "WeaponStation.FullAmmo"),
        E("Weapon.ReloadProgress", "Reload", "GetReloadStatusMax 0–1.", Direction.Read, Category.Weapons, "float", "WeaponStation.GetReloadStatusMax()"),
        E("Weapon.StationCount", "Station count", "Hardpoint count.", Direction.Read, Category.Weapons, "int", "Aircraft.weaponStations.Count"),
        E("Weapon.HasTargets", "Has targets", "CombatHUD.HasTargets.", Direction.Read, Category.Weapons, "bool", "CombatHUD.HasTargets"),
        E("Weapon.LandingMode", "Landing mode", "landingMode on CombatHUD.", Direction.Read, Category.Weapons, "bool", "CombatHUD.landingMode"),
        E("Weapon.TurretAuto", "Auto turret", "turretAutoControl.", Direction.Read, Category.Weapons, "bool", "CombatHUD.turretAutoControl"),
        E("Weapon.Lock", "Target lock", "Weapon lock / allRequirementsMet.", Direction.Read, Category.Weapons, "bool", "HUDMissileState.allRequirementsMet"),
        E("Weapon.MinRange", "Min range", "Missile minRange (HUDMissileState).", Direction.Read, Category.Weapons, "float", "HUDMissileState.minRange"),
        E("Weapon.MaxRange", "Max range", "Missile maxRange.", Direction.Read, Category.Weapons, "float", "HUDMissileState.maxRange"),
        E("Weapon.NoEscapeRange", "NEZ", "No-escape zone range.", Direction.Read, Category.Weapons, "float", "HUDMissileState.noEscapeRange"),
        E("Weapon.Alignment", "Alignment", "minAlignment for launch (HoldToLaunch).", Direction.Read, Category.Weapons, "float", "WeaponInfo.targetRequirements.minAlignment"),
        E("Weapon.TargetCount", "Target count", "targetList size.", Direction.Read, Category.Weapons, "int", "CombatHUD.targetList"),
        E("Weapon.TargetDistance", "Target distance", "Distance to primary target.", Direction.Read, Category.Weapons, "float", "derived:target"),
        E("Weapon.TargetSpeed", "Target speed", "Selected target Unit.speed.", Direction.Read, Category.Weapons, "float", "Unit.speed"),
        E("Weapon.MissileSeeker", "Seeker mode", "Missile.SeekerMode enum.", Direction.Read, Category.Weapons, "enum", "Missile.seekerMode"),
        E("Weapon.MissileEta", "Missile ETA", "Time to impact (MissileETA mod).", Direction.Read, Category.Weapons, "float", "derived:missile"),
        E("CM.FlareAmmo", "Flare ammo", "IR flare count (NO_Tactitools).", Direction.Read, Category.Countermeasures, "int", "FlareEjector.ammo"),
        E("CM.FlareMax", "Flare max", "GetMaxAmmo flares.", Direction.Read, Category.Countermeasures, "int", "FlareEjector.GetMaxAmmo()"),
        E("CM.JammerCharge", "Jammer charge", "RadarJammer PowerSupply %.", Direction.Read, Category.Countermeasures, "int", "PowerSupply.GetCharge()"),
        E("CM.ActiveIndex", "Active CM", "countermeasureManager.activeIndex.", Direction.Both, Category.Countermeasures, "byte", "CountermeasureManager.activeIndex"),
        E("CM.FlareSelected", "Flare selected", "Flare vs jammer selected.", Direction.Read, Category.Countermeasures, "bool", "derived:CM index"),
        E("EW.JamAccumulation", "HUD jam", "CombatHUD.jamAccumulation.", Direction.Read, Category.RadarEw, "float", "CombatHUD.jamAccumulation"),
        E("EW.RadarJammed", "Radar jammed", "Radar.IsJammed() (NO_Tactitools).", Direction.Read, Category.RadarEw, "bool", "Radar.IsJammed()"),
        E("EW.RadarWarningPower", "Emitter power", "OnRadarWarning.power.", Direction.Read, Category.RadarEw, "float", "Aircraft.OnRadarWarning.power"),
        E("EW.RadarDetected", "Radar detected", "OnRadarWarning.detected.", Direction.Read, Category.RadarEw, "bool", "Aircraft.OnRadarWarning.detected"),
        E("EW.MwsCount", "MWS missiles", "MissileWarning.knownMissiles count.", Direction.Read, Category.RadarEw, "int", "MissileWarning.knownMissiles"),
        E("Map.Maximized", "Map maximized", "DynamicMap.mapMaximized.", Direction.Read, Category.MapTactical, "bool", "DynamicMap.mapMaximized"),
        E("Map.DisplayFactor", "Map scale", "mapDisplayFactor.", Direction.Read, Category.MapTactical, "float", "DynamicMap.mapDisplayFactor"),
        E("Map.TrackingAge", "Track age", "Seconds since last update (TargetEstimator).", Direction.Read, Category.MapTactical, "float", "TrackingInfo age"),
        E("Map.UnitCount", "Units on map", "UnitRegistry.allUnits.", Direction.Read, Category.MapTactical, "int", "UnitRegistry.allUnits"),
        E("Gate.InFlight", "In flight", "GameManager + aircraft active.", Direction.Read, Category.GameSession, "bool", "GameManager.gameState"),
        E("Gate.OnlyWhenInFlight", "Only in flight", "speed > velocityThreshold.", Direction.Read, Category.GameSession, "bool", "Gate.OnlyWhenInFlight"),
        E("Gate.WhileAirborne", "Airborne", "radarAlt > threshold.", Direction.Read, Category.GameSession, "bool", "Unit.radarAlt", "10", Q("0.2", "1", "5", "10", "50")),
        E("Gate.WhileOnGround", "On ground", "radarAlt < threshold.", Direction.Read, Category.GameSession, "bool", "Unit.radarAlt"),
        E("Gate.FuelLow", "Low fuel", "fuelLevel below threshold.", Direction.Read, Category.GameSession, "bool", "Aircraft.fuelLevel", "0.15"),
        E("Gate.GearUp", "Gear up", "!gearDeployed.", Direction.Read, Category.GameSession, "bool", "Aircraft.gearDeployed"),
        E("Gate.GearDown", "Gear down", "gearDeployed.", Direction.Read, Category.GameSession, "bool", "Aircraft.gearDeployed"),
        E("Gate.WeaponSelected", "Weapon selected", "Active weapon station present.", Direction.Read, Category.GameSession, "bool", "WeaponManager.currentWeaponStation"),
        E("Session.Paused", "Paused", "GameplayUI.GameIsPaused.", Direction.Read, Category.GameSession, "bool", "GameplayUI.GameIsPaused"),
        E("Session.ChatActive", "Chat open", "Chat box active (NO_Tactitools).", Direction.Read, Category.GameSession, "bool", "chat.isActiveAndEnabled"),
        E("General.Constant", "Constant", "Fixed number in graph.", Direction.Read, Category.LogicGeneral, "float", "logic:constant", "0"),
        E("General.State", "State variable", "Memory between ticks.", Direction.Both, Category.LogicGeneral, "string", "logic:state"),
        E("General.Latch", "Latch", "True/false latch.", Direction.Both, Category.LogicGeneral, "bool", "logic:latch"),
        E("General.Timer", "Timer", "Seconds since event.", Direction.Both, Category.LogicGeneral, "float", "logic:timer"),
        E("General.Counter", "Counter", "Integer counter.", Direction.Both, Category.LogicGeneral, "int", "logic:counter"),
        E("General.Expression", "Expression", "Formula over inputs.", Direction.Read, Category.LogicGeneral, "float", "logic:expr"),
        E("General.Input", "Graph input", "Value from another port.", Direction.Read, Category.LogicGeneral, "float", "logic:input"),
        E("General.NextNode", "Next node", "Chain transition.", Direction.Write, Category.LogicGeneral, "string", "logic:next"),
        W("aoa-label", "AoA label", "Angle-of-attack overlay text on FlightHud.", Category.HudFlightHud, "string", "FlightHud overlay id", "AoA"),
        W("aoa-value", "AoA value", "AoA number on overlay.", Category.HudFlightHud, "string", "overlay", "15°"),
        W("aoa-warn", "AoA warning", "Warn overlay on stall.", Category.HudFlightHud, "Color", "overlay", "#FF4400"),
        W("stall-label", "STALL label", "STALL text.", Category.HudFlightHud, "string", "overlay", "STALL"),
        W("speed-label", "Speed label", "IAS/TAS overlay.", Category.HudFlightHud, "string", "overlay"),
        W("ias-label", "IAS label", "Indicated airspeed text.", Category.HudFlightHud, "string", "SpeedGauge.airspeedDisplay"),
        W("alt-label", "Altitude label", "Altitude overlay.", Category.HudFlightHud, "string", "Altitude.radarAlt"),
        W("vs-label", "V/S label", "Vertical speed overlay.", Category.HudFlightHud, "string", "Climbrate"),
        W("fuel-label", "Fuel label", "Fuel overlay text.", Category.HudFlightHud, "string", "FuelGauge.fuelReading"),
        W("fuel-warn", "Fuel warn", "Low fuel warning color/text.", Category.HudFlightHud, "Color", "overlay", "#FFAA00"),
        W("g-label", "G label", "G-force overlay.", Category.HudFlightHud, "string", "GIndicators"),
        W("warn-label", "Generic warn", "Generic warning label.", Category.HudFlightHud, "string", "overlay", "WARN"),
        W("aoa-text", "AoA text (vanilla)", "AoADisplay.AoAText.text.", Category.HudGauges, "string", "AoADisplay.AoAText", "12°"),
        W("aoa-root", "AoA root", "AoADisplay root.", Category.HudGauges, "bool", "AoADisplay.gameObject"),
        W("speed-text", "Speed text", "SpeedGauge.airspeedDisplay.", Category.HudGauges, "string", "SpeedGauge.airspeedDisplay"),
        W("alt-text", "Alt text", "Altitude.radarAlt / absAlt.", Category.HudGauges, "string", "Altitude.radarAlt"),
        W("g-text", "G text", "GIndicators text.", Category.HudGauges, "string", "GIndicators"),
        W("fuel-text", "Fuel text", "FuelGauge.fuelReading.", Category.HudGauges, "string", "FuelGauge.fuelReading"),
        W("hud-root", "HUD canvas", "Entire FlightHud canvas active.", Category.HudFlightHud, "bool", "FlightHud.canvas"),
        W("hud.compass", "Compass UV", "Heading via compass.uvRect.", Category.HudFlightHud, "float", "FlightHud.compass.uvRect"),
        W("hud.pitchLadder", "Pitch ladder", "pitchCompass uvRect/scale.", Category.HudFlightHud, "float", "FlightHud.pitchCompass"),
        W("hud.velocityVector", "Velocity vector", "velocityVector color/position.", Category.HudFlightHud, "Color", "FlightHud.velocityVector.color"),
        W("hud.waterline", "Waterline", "Waterline image visible/color.", Category.HudFlightHud, "bool", "FlightHud.waterline"),
        W("hud.notchLine", "Notch line", "MKMods notch direction line.", Category.HudFlightHud, "Color", "MKMods HUDNotchLine", "#FF0000"),
        W("combat.targetDesignator", "Target designator", "CombatHUD.targetDesignator color/pos.", Category.CombatHud, "Color", "CombatHUD.targetDesignator"),
        W("combat.targetText", "Target text", "targetText / targetInfo.", Category.CombatHud, "string", "CombatHUD.targetText"),
        W("combat.countermeasureText", "CM text", "Countermeasure name/ammo text.", Category.CombatHud, "string", "CombatHUD countermeasure Text"),
        W("combat.countermeasureColor", "CM color", "Countermeasure Image.color.", Category.CombatHud, "Color", "CombatHUD countermeasure Image"),
        W("combat.hitMarker", "Hit marker", "Hit marker flash.", Category.CombatHud, "bool", "CombatHUD.hitMarker"),
        W("combat.missileHint", "Missile hint", "HUDMissileState hint text.", Category.CombatHud, "string", "HUDMissileState.hint"),
        W("combat.ccipPipper", "CCIP pipper", "Bombing CCIP marker.", Category.CombatHud, "Color", "HUDBombingState.ccipPipper"),
        W("status.fuel", "Status fuel", "SystemStatusDisplay fuel img/txt.", Category.HudGauges, "Color", "SystemStatusDisplay.systemFuelImg"),
        W("status.gear", "Status gear", "Gear indicator color.", Category.HudGauges, "Color", "SystemStatusDisplay.systemGearImg"),
        W("status.radar", "Status radar", "Radar status color.", Category.HudGauges, "Color", "SystemStatusDisplay.systemRadarImg"),
        W("status.engine", "Status engine", "Engine status.", Category.HudGauges, "Color", "SystemStatusDisplay.systemEngineImg"),
        W("mfd.speed", "MFD speed", "VirtualMFD.speed text.", Category.MfdHmd, "string", "VirtualMFD.speed"),
        W("mfd.altitude", "MFD altitude", "VirtualMFD.altitude.", Category.MfdHmd, "string", "VirtualMFD.altitude"),
        W("mfd.missionTime", "MFD mission time", "TMP missionTime.", Category.MfdHmd, "string", "VirtualMFD.missionTime"),
        W("mfd.attitude", "MFD attitude", "Attitude indicator fill/rotation.", Category.MfdHmd, "float", "VirtualMFD.attitude"),
        W("hmd.horizon", "HMD horizon", "HeadMountedDisplay horizon.", Category.MfdHmd, "float", "HeadMountedDisplay.horizon"),
        W("map.overlayColor", "Map overlay", "DynamicMap overlay color (TacticalMapLayers).", Category.MapTactical, "Color", "DynamicMap.iconLayer overlay"),
        W("map.frontline", "Front line", "Frontline polyline (FrontlineMap).", Category.MapTactical, "Color", "DynamicMap overlay polyline"),
        W("map.unitIconColor", "Icon color", "UnitMapIcon color (FactionColors).", Category.MapTactical, "Color", "UnitMapIcon.color"),
        W("map.radarCone", "Radar cone", "TacScreen radarCone color.", Category.MapTactical, "Color", "TacScreen.radarCone"),
        W("stallHorn", "Stall horn", "AoADisplay stall horn clip.", Category.Audio, "AudioClip", "AoADisplay.stallHorn"),
        W("stallWarning", "Stall voice", "Voice stall warning.", Category.Audio, "AudioClip", "AoADisplay.stallVoice"),
        W("overspeed", "Overspeed", "SpeedGauge overspeed voice.", Category.Audio, "AudioClip", "SpeedGauge.overspeedVoice"),
        W("pullUp", "Pull up", "Pull up voice warning.", Category.Audio, "AudioClip", "voice:pullUp"),
        W("warningBeep", "Warning beep", "Generic beep.", Category.Audio, "AudioClip", "UI warning"),
        W("lockTone", "Lock tone", "Missile lock tone.", Category.Audio, "AudioClip", "CombatHUD lock"),
        W("missileLaunch", "Missile launch", "Launch sound.", Category.Audio, "AudioClip", "weapon launch"),
        W("weaponRipple", "Ripple", "Salvo ripple sound.", Category.Audio, "AudioClip", "WeaponManager"),
        W("clickUI", "UI click", "Interface click.", Category.Audio, "AudioClip", "SoundManager"),
        W("voice.flare", "Voice: Flare", "MKMods IR warning voice.", Category.Audio, "AudioClip", "MKMods:Flare"),
        W("voice.notch", "Voice: Notch", "MKMods ARH notch voice.", Category.Audio, "AudioClip", "MKMods:Notch"),
        W("voice.lowFuel", "Voice: Low fuel", "MKMods low fuel.", Category.Audio, "AudioClip", "MKMods:lowFuel"),
        W("voice.bingo", "Voice: Bingo", "MKMods bingo fuel.", Category.Audio, "AudioClip", "MKMods:bingo"),
        W("music.takeoff", "Takeoff music", "AircraftParameters.takeoffMusic / CrossFade.", Category.Audio, "AudioClip", "MusicManager.CrossFadeMusic"),
        W("camera.fov", "Camera FOV", "mainCamera.fieldOfView (GlocCamera).", Category.Camera, "float", "Camera.fieldOfView", "50", Q("30", "40", "50", "60", "70", "90")),
        W("camera.position", "Camera position", "Cockpit cam localPosition.", Category.Camera, "Vector3", "CameraCockpitState cam transform"),
        W("camera.shake", "Camera shake", "AddShake low/high freq.", Category.Camera, "float", "CameraCockpitState.AddShake"),
        W("settings.hudColor", "HUD color", "PlayerSettings hudColorR/G/B.", Category.PlayerSettings, "Color", "PlayerSettings.hudColorR/G/B", "#00FF00"),
        W("settings.hudTextSize", "HUD text size", "hudTextSize.", Category.PlayerSettings, "float", "PlayerSettings.hudTextSize", "40", Q("24", "32", "40", "48", "56")),
        W("settings.lagPip", "Lag pip", "Lag pip toggle.", Category.PlayerSettings, "bool", "PlayerSettings.lagPip"),
        W("settings.rangeCircle", "Range circle", "Range circle on HUD.", Category.PlayerSettings, "bool", "PlayerSettings.rangeCircle"),
        W("settings.gauges", "Gauges", "Show gauges.", Category.PlayerSettings, "bool", "PlayerSettings.gauges"),
        W("state.flag", "State flag", "Bool flag in state store.", Category.LogicGeneral, "bool", "logic:state.flag", "true"),
        W("state.count", "State count", "Int counter in state.", Category.LogicGeneral, "int", "logic:state.count"),
        W("state.lastValue", "Last value", "Last stored value.", Category.LogicGeneral, "float", "logic:state.lastValue"),

        // ── Read.* aliases (common dump fields) ──
        E("Read.Aircraft.speed", "Speed (Aircraft)", "Aircraft.speed, m/s.", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.speed", "80", Q("0", "10", "50", "80", "100", "150")),
        E("Read.Aircraft.fuelLevel", "Fuel (Aircraft)", "Aircraft.fuelLevel 0–1.", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.fuelLevel", "0.15", Q("0.05", "0.1", "0.15", "0.2", "0.25", "0.5", "1")),
        E("Read.Unit.radarAlt", "Altitude (Unit)", "Unit.radarAlt AGL.", Direction.Read, Category.FlightTelemetry, "float", "Unit.radarAlt", "100", Q("0", "0.2", "1", "5", "10", "50", "100", "500")),
        E("Read.Unit.speed", "Speed (Unit)", "Unit.speed, m/s.", Direction.Read, Category.FlightTelemetry, "float", "Unit.speed"),
        E("Read.Aircraft.gForce", "G (Aircraft)", "Aircraft.gForce.", Direction.Read, Category.FlightTelemetry, "float", "Aircraft.gForce", "3", Q("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
        E("Read.CombatHUD.jamAccumulation", "HUD jam", "CombatHUD.jamAccumulation.", Direction.Read, Category.RadarEw, "float", "CombatHUD.jamAccumulation"),
        E("Read.WeaponStation.Ammo", "Station ammo", "WeaponStation.Ammo.", Direction.Read, Category.Weapons, "int", "WeaponStation.Ammo", "4", Q("0", "1", "2", "4", "8")),
        E("Read.DynamicMap.mapDisplayFactor", "Map scale", "DynamicMap.mapDisplayFactor.", Direction.Read, Category.MapTactical, "float", "DynamicMap.mapDisplayFactor"),
        E("Read.PlayerSettings.hudTextSize", "HUD text size", "PlayerSettings.hudTextSize.", Direction.Read, Category.PlayerSettings, "float", "PlayerSettings.hudTextSize", "40", Q("24", "32", "40", "48", "56")),

        E("Compare.Hysteresis", "Hysteresis", "Different on/off thresholds.", Direction.Read, Category.CompareMode, "bool", "logic:compare:hyst"),
        E("Compare.Changed", "Changed", "value != previous.", Direction.Read, Category.CompareMode, "bool", "logic:compare:changed"),
        E("Compare.RateLimit", "Rate limit", "No more than N times/sec.", Direction.Read, Category.CompareMode, "bool", "logic:compare:rate"),
        E("Compare.GreaterThan", "Greater than", "value > threshold.", Direction.Read, Category.CompareMode, "bool", "logic:compare:gt"),
        E("Compare.LessThan", "Less than", "value < threshold.", Direction.Read, Category.CompareMode, "bool", "logic:compare:lt"),
        E("Compare.Equals", "Equals", "value == threshold.", Direction.Read, Category.CompareMode, "bool", "logic:compare:eq"),
        E("Compare.NotEquals", "Not equals", "value != threshold.", Direction.Read, Category.CompareMode, "bool", "logic:compare:ne"),
        E("Compare.InRange", "In range", "min <= value <= max.", Direction.Read, Category.CompareMode, "bool", "logic:compare:in"),
        E("Compare.OutsideRange", "Outside range", "value < min || value > max.", Direction.Read, Category.CompareMode, "bool", "logic:compare:out"),
        E("Compare.CrossedAbove", "Crossed above", "Was below, now above.", Direction.Read, Category.CompareMode, "bool", "logic:compare:crossUp"),
        E("Compare.CrossedBelow", "Crossed below", "Was above, now below.", Direction.Read, Category.CompareMode, "bool", "logic:compare:crossDown"),
        E("Compare.Debounce", "Debounce", "Stable for N sec.", Direction.Read, Category.CompareMode, "bool", "logic:compare:debounce"),
        E("Compare.StableFor", "Stable for", "Unchanged for N sec.", Direction.Read, Category.CompareMode, "bool", "logic:compare:stable"),
        E("Action.SetOverlayColor", "Overlay color", "Set overlay/HUD element Color.", Direction.Write, Category.OutputAction, "Color", "overlay.color"),
        E("Action.SetOverlayVisible", "Overlay visibility", "Show/hide overlay.", Direction.Write, Category.OutputAction, "bool", "overlay.SetActive"),
        E("Action.SetHudText", "HUD text", "Text.text on HUD element.", Direction.Write, Category.OutputAction, "string", "Text.text"),
        E("Action.SetHudColor", "HUD color", "Image.color vanilla gauge.", Direction.Write, Category.OutputAction, "Color", "Image.color"),
        E("Action.SetHudActive", "HUD active", "GameObject/Canvas active.", Direction.Write, Category.OutputAction, "bool", "GameObject.SetActive"),
        E("Action.SetFontSize", "Font size", "HUD text font size.", Direction.Write, Category.OutputAction, "int", "Text.fontSize", "14", Q("10", "12", "14", "16", "18", "22", "28")),
        E("Action.FadeIn", "Fade in", "Smooth alpha fade in.", Direction.Write, Category.OutputAction, "float", "CanvasGroup.alpha", "0.5"),
        E("Action.FadeOut", "Fade out", "Smooth alpha fade out.", Direction.Write, Category.OutputAction, "float", "CanvasGroup.alpha", "0.5"),
        E("Action.ResetDefault", "Reset", "Restore vanilla value.", Direction.Write, Category.OutputAction, "void", "RefreshSettings()"),
        E("Action.PlaySound", "Play sound", "AudioSource.PlayOneShot.", Direction.Write, Category.OutputAction, "AudioClip", "AudioSource.Play"),
        E("Action.StopSound", "Stop sound", "Stop AudioSource.", Direction.Write, Category.OutputAction, "void", "AudioSource.Stop"),
        E("Action.ThenAfter", "Then after", "Delay before next action.", Direction.Write, Category.OutputAction, "float", "logic:delay"),
        E("Logic.SetState", "Set state", "Write state key/value.", Direction.Write, Category.OutputAction, "string", "logic:state:set")
    ];

    private static MethodEntry[] BuildCuratedMethods() =>
    [
        M("Method.FlightHud.EnableCanvas", "Enable HUD canvas", "FlightHud.EnableCanvas(bool) — show/hide entire HUD.", Category.HudFlightHud, "FlightHud.EnableCanvas", "void", "enable: bool"),
        M("Method.FlightHud.GetHUDCenter", "HUD center", "Center reticle Transform.", Category.HudFlightHud, "FlightHud.GetHUDCenter", "Transform", "—"),
        M("Method.FlightHud.RefreshSettings", "Refresh HUD", "Re-read PlayerSettings on HUD.", Category.HudFlightHud, "FlightHud.RefreshSettings", "void", "—"),
        M("Method.CombatHUD.GetTargetList", "Target list", "Get List<Unit> targets.", Category.Weapons, "CombatHUD.GetTargetList", "List<Unit>", "—"),
        M("Method.CombatHUD.AddTarget", "Add target", "AddTargetList + SelectMarker.", Category.Weapons, "CombatHUD + WeaponManager", "void", "unit: Unit"),
        M("Method.CombatHUD.DeselectAll", "Deselect targets", "DeselectAll targets.", Category.Weapons, "CombatHUD.DeselectAll", "void", "—"),
        M("Method.Aircraft.GetInputs", "Get inputs", "ControlInputs: pitch, roll, yaw, throttle.", Category.PilotInputs, "Aircraft.GetInputs", "ControlInputs", "—"),
        M("Method.Aircraft.GetFuelLevel", "Get fuel", "Fuel 0–1.", Category.FlightTelemetry, "Aircraft.GetFuelLevel", "float", "—"),
        M("Method.WeaponManager.SetActiveStation", "Switch station", "SetActiveStation(byte index).", Category.Weapons, "WeaponManager.SetActiveStation", "void", "index: byte"),
        M("Method.WeaponManager.AddTarget", "Add target", "AddTargetList — add target.", Category.Weapons, "WeaponManager.AddTargetList", "void", "unit: Unit"),
        M("Method.Countermeasure.SetFlare", "Select flare", "activeIndex = flare.", Category.Countermeasures, "CountermeasureManager.activeIndex", "void", "—"),
        M("Method.Countermeasure.SetJammer", "Select jammer", "activeIndex = jammer.", Category.Countermeasures, "CountermeasureManager.activeIndex", "void", "—"),
        M("Method.Pilot.Fire", "Fire (gate)", "Pilot.Fire — can block via Prefix.", Category.Weapons, "Pilot.Fire", "bool", "Harmony gate"),
        M("Method.MusicManager.CrossFade", "CrossFade music", "Music change / takeoff repeat.", Category.Audio, "MusicManager.CrossFadeMusic", "void", "clip, flags"),
        M("Method.CameraCockpit.UpdateState", "Camera UpdateState", "FOV + position (GlocCamera patch).", Category.Camera, "CameraCockpitState.UpdateState", "void", "—"),
        M("Method.NightVision.UpdateGain", "NVG gain", "Night vision gain (skip/replace).", Category.Camera, "NightVision.UpdateGain", "void", "—"),
        M("Method.DynamicMap.UpdateIcons", "Update map icons", "Throttled map refresh (Perf mod).", Category.MapTactical, "DynamicMap.UpdateIcons", "void", "—"),
        M("Method.GameManager.SetGameState", "Set game state", "Change GameState.", Category.GameSession, "GameManager.SetGameState", "void", "state: GameState"),
        M("Method.PlayerSettings.ApplyPrefs", "Apply prefs", "Apply HUD settings.", Category.PlayerSettings, "PlayerSettings.ApplyPrefs", "void", "—"),
        M("Method.SoundManager.PlayInterface", "Play UI sound", "PlayInterfaceOneShot.", Category.Audio, "SoundManager.PlayInterfaceOneShot", "void", "clip: AudioClip")
    ];
}
